Added support for image integral computation.
SixLabors/ImageSharp pull request #1536
Opened 2021-02-07 05:06 UTC by rold2007

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/SixLabors/ImageSharp/pulls) open
- [x] I have verified that I am following matches the existing coding patterns and practice as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x] I have provided test coverage for my change (where applicable)

### Description
This pull request replaces [this one](https://github.com/SixLabors/ImageSharp/pull/1441).

2021-02-09 04:56 UTC, JimBobSquarePants requested changes
Looks good. Thanks for resubmitting after I messed up!

Just some minor organizations changes, the code looks good 👍

2021-02-09 04:56 UTC, JimBobSquarePants commented on src/ImageSharp/Processing/Extensions/Transforms/ImagingUtilities.cs
> +    public static class ImagingUtilities
The only thing I would change is to make the existing `ProcessingExtensions` partial and rename this one to match. `ProcessingExtensions.IntegralImage.cs`. I'd also move it to the same `Processing/Extensions/` folder.

2021-02-09 04:56 UTC, JimBobSquarePants commented on src/ImageSharp/Processing/Extensions/Transforms/ImagingUtilities.cs
> +        /// Apply an image integral. See https://en.wikipedia.org/wiki/Summed-area_table
You can use `<see href="https://en.wikipedia.org/wiki/Summed-area_table"/>` to better work with intellisense docs.

2021-02-09 04:56 UTC, JimBobSquarePants commented on tests/ImageSharp.Tests/Processing/Transforms/ImagingUtilitiesTests.cs
> +namespace SixLabors.ImageSharp.Tests.Processing.Transforms
Move to `tests/ImageSharp.Tests/Processing/` and rename class.

2021-02-17 01:43 UTC, closed without merging

2021-02-17 01:46 UTC, JimBobSquarePants commented
Sorry @rold2007 

We just added Git LFS to the repository and it's rewritten the history. This has forced the PR to be closed and I cannot reopen it. 

If you like I can create a new PR based upon your work to save you the effort of redoing it?

2021-02-17 12:17 UTC, rold2007 commented
@JimBobSquarePants No worries. I'll open a new PR myself.

2021-02-17 12:21 UTC, JimBobSquarePants commented
Thanks @rold2007 !!